# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  displayName: 'build verademo'
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m -ntp'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
  
- task: Bash@3
  displayName: 'Veracode SCA scan'
  inputs:
    script: |
      export SRCCLR_SCM_URI=https://github.com/christyson/verademo
      export SRCCLR_API_TOKEN="$(SRCCLR_API_TOKEN)"
      export SRCCLR_SCM_REF=master
      export SRCCLR_SCM_REF_TYPE=branch
      export SRCCLR_SCM_REV=123456
      curl -sSL https://download.sourceclear.com/ci.sh | bash -s -- scan --update-advisor