# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: mvn -ntp package
  displayName: 'build verademo'

- script: |
      export SRCCLR_SCM_URI=https://github.com/christyson/verademo
      export SRCCLR_API_TOKEN="$(SRCCLR_API_TOKEN)"
      curl -sSL https://download.sourceclear.com/ci.sh | bash -s -- scan --skip-compile --update-advisor
  displayName: 'Veracode SCA scan'
 
